
---
skip:
  # (uncomment to skip tests based on path)
  # paths:
    # - time-clip-to-integer.js # https://bugs.webkit.org/show_bug.cgi?id=185563
  features:
    - SharedArrayBuffer
    - Atomics
    # https://bugs.webkit.org/show_bug.cgi?id=179001
    - BigInt
    # https://bugs.webkit.org/show_bug.cgi?id=166693
    - async-iteration
    # https://bugs.webkit.org/show_bug.cgi?id=186686
    - Symbol.prototype.description
    # String.prototype.matchAll / Symbol.matchAll
    - String.prototype.matchAll
    - Symbol.matchAll
  files:
    - test/built-ins/Array/prototype/reverse/length-exceeding-integer-limit-with-object.js
    - test/built-ins/Array/prototype/unshift/length-near-integer-limit.js

    # https://bugs.webkit.org/show_bug.cgi?id=185495
    - test/built-ins/Array/prototype/slice/S15.4.4.10_A3_T1.js
    - test/built-ins/Array/prototype/slice/S15.4.4.10_A3_T2.js
    - test/built-ins/Array/prototype/slice/create-non-array-invalid-len.js
    - test/built-ins/Array/prototype/slice/create-proxied-array-invalid-len.js
    - test/built-ins/Array/prototype/splice/create-species-undef-invalid-len.js
    - test/built-ins/Array/prototype/splice/create-non-array-invalid-len.js
    - test/built-ins/Array/prototype/splice/create-species-undef-invalid-len.js
    - test/built-ins/Array/prototype/splice/length-near-integer-limit-grow-array.js

    # https://bugs.webkit.org/show_bug.cgi?id=185625
    - test/built-ins/Array/prototype/indexOf/15.4.4.14-3-28.js
    - test/built-ins/Array/prototype/indexOf/15.4.4.14-3-29.js

    # https://bugs.webkit.org/show_bug.cgi?id=164456
    - test/built-ins/Array/prototype/lastIndexOf/15.4.4.15-3-28.js
    - test/built-ins/Array/prototype/pop/S15.4.4.6_A3_T2.js
    - test/built-ins/Array/prototype/push/S15.4.4.7_A4_T1.js
    - test/built-ins/Array/prototype/push/length-near-integer-limit.js

    # Support Unicode 11
    # https://bugs.webkit.org/show_bug.cgi?id=186685
    - test/built-ins/RegExp/property-escapes/character-class.js
    - test/built-ins/RegExp/property-escapes/generated/XID_Start.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Mongolian.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Currency_Symbol.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Sogdian.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Kaithi.js
    - test/built-ins/RegExp/property-escapes/generated/Ideographic.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Han.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Gunjala_Gondi.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Hanifi_Rohingya.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Sogdian.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Inherited.js
    - test/built-ins/RegExp/property-escapes/generated/Emoji.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Malayalam.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Old_Sogdian.js
    - test/built-ins/RegExp/property-escapes/generated/ID_Start.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Nonspacing_Mark.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Han.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Dogra.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Dogra.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Gunjala_Gondi.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Kannada.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Gurmukhi.js
    - test/built-ins/RegExp/property-escapes/generated/Emoji_Component.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Makasar.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Medefaidrin.js
    - test/built-ins/RegExp/property-escapes/generated/Sentence_Terminal.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Kannada.js
    - test/built-ins/RegExp/property-escapes/generated/Alphabetic.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Decimal_Number.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Makasar.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Georgian.js
    - test/built-ins/RegExp/property-escapes/generated/Terminal_Punctuation.js
    - test/built-ins/RegExp/property-escapes/generated/XID_Continue.js
    - test/built-ins/RegExp/property-escapes/generated/Unified_Ideograph.js
    - test/built-ins/RegExp/property-escapes/generated/Changes_When_Uppercased.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Gurmukhi.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Punctuation.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Other.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Georgian.js
    - test/built-ins/RegExp/property-escapes/generated/Diacritic.js
    - test/built-ins/RegExp/property-escapes/generated/Changes_When_NFKC_Casefolded.js
    - test/built-ins/RegExp/property-escapes/generated/Cased.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Spacing_Mark.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Devanagari.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Soyombo.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Tirhuta.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Kharoshthi.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Latin.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Latin.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Letter.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Newa.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Other_Letter.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Soyombo.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Kaithi.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Ahom.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Other_Punctuation.js
    - test/built-ins/RegExp/property-escapes/generated/Grapheme_Base.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Bengali.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Telugu.js
    - test/built-ins/RegExp/property-escapes/generated/Lowercase.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Newa.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Bopomofo.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Arabic.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Number.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Chakma.js
    - test/built-ins/RegExp/property-escapes/generated/Bidi_Mirrored.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Ahom.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Other_Number.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Tangut.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Bengali.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Common.js
    - test/built-ins/RegExp/property-escapes/generated/Changes_When_Casefolded.js
    - test/built-ins/RegExp/property-escapes/generated/Changes_When_Casemapped.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Hebrew.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Tamil.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Mark.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Other_Symbol.js
    - test/built-ins/RegExp/property-escapes/generated/Grapheme_Extend.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Grantha.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Mongolian.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Nko.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Armenian.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Format.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Lowercase_Letter.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Symbol.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Nko.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Khojki.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Medefaidrin.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Hanifi_Rohingya.js
    - test/built-ins/RegExp/property-escapes/generated/Changes_When_Lowercased.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Oriya.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Devanagari.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Uppercase_Letter.js
    - test/built-ins/RegExp/property-escapes/generated/Extended_Pictographic.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Kharoshthi.js
    - test/built-ins/RegExp/property-escapes/generated/Emoji_Modifier_Base.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Hebrew.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Unassigned.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Armenian.js
    - test/built-ins/RegExp/property-escapes/generated/Emoji_Presentation.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Tangut.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Bopomofo.js
    - test/built-ins/RegExp/property-escapes/generated/Uppercase.js
    - test/built-ins/RegExp/property-escapes/generated/Assigned.js
    - test/built-ins/RegExp/property-escapes/generated/ID_Continue.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Common.js
    - test/built-ins/RegExp/property-escapes/generated/Changes_When_Titlecased.js
    - test/built-ins/RegExp/property-escapes/generated/Case_Ignorable.js
    - test/built-ins/RegExp/property-escapes/generated/General_Category_-_Cased_Letter.js
    - test/built-ins/RegExp/property-escapes/generated/Script_Extensions_-_Telugu.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Old_Sogdian.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Arabic.js
    - test/built-ins/RegExp/property-escapes/generated/Script_-_Chakma.js

    # [[OwnPropertyKeys]] order with large integer index keys up to 2 ** 53 - 1
    # https://bugs.webkit.org/show_bug.cgi?id=186691
    - test/built-ins/Reflect/ownKeys/return-on-corresponding-order-large-index.js
